First step refactoring
Vixroff/LearnPython_project pull request #10
Opened 2022-06-22 10:57 UTC by Vixroff

2022-06-25 12:43 UTC, kazauwa requested changes

2022-06-25 12:43 UTC, kazauwa commented on webapp/sections/views.py
> +def search_sections(form):
Идея вынести поиск в отдельную функцию - отличная, надо только её немного докруить.

Давай представим, что у нас появится ещё одно место в проекте, где мы захотим искать секции. Например, сделаем какой-нибудь API, где данные для фильтрации будут передаваться не через форму. И тогда мы не сможем переиспользовать эту функцию. Поэтому давай сделаем так, чтобы она на вход принимала все необходимые данные, чтобы их можно было сразу же подставить.

2022-06-25 12:43 UTC, kazauwa commented on webapp/sections/views.py
> +            flash('Нет свободных помещений по вашему запросу, пожалуйста, свяжитесь с нами, и мы поможем Вам с выбором.',
flash никак не относится к поиску. Функция не должна знать откуда её вызвали, ей должно быть всё равно. Она должна выполнять свою задачу и возвращать результат. Почитай про [чистые функции](https://dvmn.org/encyclopedia/clean_code/decomposition_pure_functions/)

2022-06-25 12:43 UTC, kazauwa commented on webapp/sections/views.py
>              return None
```suggestion
            return
```
Можно не добавлять `None`. Пустой ретёрн и так возвращает. Кстати, если в конце функции не написать return, то тоже вернётся None.

2022-06-25 12:43 UTC, kazauwa commented on webapp/sections/views.py
> +        flash('Некорректно введены данные.', category='error')
Выше я написал замечание про flash, и здесь ты можешь резонно возразить, мол как тогда правильно вернуть ошибку? К сожалению, в питоне нет механизма, который позволял бы возвращать ошибку отдельно от результата (как в Rust или Go например), да и так делать не принято. Плюс, валидация данных не относится к поиску.
Предлагаю вынести проверку `if form.validate_on_submit and form.area_min.data <= form.area_max.data:` отсюда в метод в форму таким образом:
```
from wtforms import ValidationError

class RentFilterForm(FlaskForm):
    ...

    def validate(self, extra_validators=None):
        result = self.super().validate(extra_validators=extra_validators)
        if not result:
            return result
        if not form.validate_on_submit and form.area_min.data <= form.area_max.data:
            raise ValidationError('Некорректно введены данные.')
        return True
```

Выдаю ответ, чтобы сейчас не зацикливаться на ООП. На следующем звонке могу рассказать подробнее что здесь вообще происходит.

2022-06-25 12:43 UTC, kazauwa commented on webapp/templates/sections/find_section.html
> +    {{ form_1.submit1 }}
Давай назовём форму как-нибудь понятно, а не form_1

2022-06-25 12:43 UTC, kazauwa commented on webapp/templates/tenants/find_tenant.html
> +        {{ form_2.name.label }}
И здесь тоже давай переименуем

2022-06-26 18:49 UTC, Vixroff commented on webapp/forms.py
> +    submit1 = SubmitField('Применить фильтр')
Я не знаю почему так происходит, но если назвать просто submit в обеих формах, то они как -будто объединяются и наше условие(request.method == 'POST' and find_tenant_form.submit2.data) не срабатывает в таком случае и компании не находятся. Проверял несколько раз

2022-06-26 19:02 UTC, Vixroff commented on webapp/sections/views.py
> +def search_sections(form):
и здесь тоже как-то странно, в таком виде я запушил свой первый коммит, но далее видоизменил. сейчас функция выглядит так:
def search_sections(func, area_min, area_max):

2022-06-26 19:53 UTC, Vixroff commented on webapp/sections/views.py
> +def search_sections(form):
Таких данных будет достаточно?

2022-06-27 18:37 UTC, kazauwa requested changes

2022-06-27 18:37 UTC, kazauwa commented on add_data.py
> +from webapp import db
```suggestion
from webapp import db
```

2022-06-27 18:37 UTC, kazauwa commented on config.py
> +    YANDEX_API_KEY_MAP = '4e365bd6-9813-4000-95f3-a859675b0dcc'
Не надо палить всякие секретные ключи и пароли в конфигах.
Сделай как с SECRET_KEY, клади ключик в переменную окружения и доставай его через `os.environ.get` или `os.getenv`

2022-06-27 18:37 UTC, kazauwa commented on webapp/__init__.py
> +    @app.route('/', methods=['GET', 'POST'])
Не нужно класть роуты в create_app(). Вытащи их наружу и так же через current_app регистрируй:
```
@current_app.route('/', methods=['GET', 'POST']):
    ...
```

2022-06-27 18:37 UTC, kazauwa commented on webapp/__init__.py
> +                print('a')
Забыл убрать дебажный принт

2022-06-27 18:37 UTC, kazauwa commented on webapp/__init__.py
> +            print(session.get('func'), session.get('area_min'), session.get('area_max'))
И этот тоже

2022-06-27 18:37 UTC, kazauwa commented on webapp/__init__.py
> +            print('b')
И этот

2022-06-27 22:42 UTC, Vixroff commented on webapp/__init__.py
> +    @app.route('/', methods=['GET', 'POST'])
получаю такую штуку:

    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.

2022-06-28 19:55 UTC, kazauwa approved these changes

2022-06-28 19:58 UTC, merged