Work with data
Vixroff/LearnPython_project pull request #7
Opened 2022-06-10 22:05 UTC by Ralaam1

Функция **def tenants_in_section** не доделана. Не получается добиться работы цикла if в форме _show_sections.html_.

Хочу сделать: **if** _id_арендатора_ **!=0**:
                                 **{{** _арендатор_ **}}**
                      **else**:
                                   <h2> Секция свободна </h2>

Почему-то выдаёт 404 или 500 ошибки.

2022-06-10 22:09 UTC, Ralaam1 commented on webapp/routes.py
> +from db import db_session
Косяк

2022-06-10 22:10 UTC, Ralaam1 commented on webapp/routes.py
> +
Выше косяк(

2022-06-11 17:45 UTC, kazauwa requested changes

2022-06-11 17:45 UTC, kazauwa commented on model.py
> +        return f"{self.sections}, {self.index}"
Есть у меня подозрения, что в representation здания должны быть какие-то свойства, которые это здание описывают. Например улица и индекс (название?). Если я правильно, сейчас `print(building)` выплюнет кучу айдишников

2022-06-11 17:45 UTC, kazauwa commented on requirements.txt
> +"Для возможности автоматического создания переменной среды (текстовая переменная системы, хранящая какую-либо информацию), которая прописана в файле >.flaskenv<.
В requirements.txt должны быть только зависимости, по одной штуке на строчке.
Если очень хочется сделать документацию, то её стоит положить в `README.md` (см. [пример](https://dvmn.org/encyclopedia/tutorial/tutorial_readme/))

2022-06-11 17:45 UTC, kazauwa commented on webapp/login_forms.py
> +from flask_wtf import FlaskForm
У нас планируется какой-то личный кабинет в этом проекте?

2022-06-11 17:45 UTC, kazauwa commented on webapp/routes.py
> +
Какой косяк?

2022-06-11 17:45 UTC, kazauwa commented on webapp/templates/login_page.html
> +      .bd-placeholder-img {
В идеале бы стили вынести в css файлы

2022-06-11 17:45 UTC, kazauwa commented on webapp/templates/login_page.html
> +      .bd-placeholder-img {
Все стили, не только на этой странице

2022-06-11 17:45 UTC, kazauwa commented on webapp/templates/show_sections.html
> +        <a href="/tenants">Арендует</a>
Вопрос: здесь по задумке перекидывает страницу со всеми арендаторами?

2022-06-11 17:50 UTC, Ralaam1 commented on webapp/templates/show_sections.html
> +        <a href="/tenants">Арендует</a>
Вчера в цикл не смог правильный я(

2022-06-11 17:52 UTC, Ralaam1 commented on webapp/login_forms.py
> +from flask_wtf import FlaskForm
Максим же хотел с разными правами доступа и кабинетом вроде?

2022-06-11 18:06 UTC, Ralaam1 commented on model.py
> +        return f"{self.sections}, {self.index}"
это я дандр методы изучал

2022-06-11 18:41 UTC, kazauwa commented on webapp/login_forms.py
> +from flask_wtf import FlaskForm
@Vixroff, помоги нам)

2022-06-11 18:41 UTC, kazauwa commented on model.py
> +        return f"{self.sections}, {self.index}"
Моё увожение
Но проблема остаётся актуальной)

2022-06-11 18:51 UTC, Vixroff commented on webapp/login_forms.py
> +from flask_wtf import FlaskForm
Это Андрея идея была, я просто подумал в каком виде это может быть)

2022-06-11 18:52 UTC, Vixroff commented on webapp/routes.py
> +
😮‍💨

2022-06-11 18:59 UTC, Vixroff commented on webapp/login_forms.py
> +from flask_wtf import FlaskForm
Я считаю, что имеет место быть, но не первостепенная задача)

2022-06-12 10:58 UTC, kazauwa approved these changes

2022-06-12 11:03 UTC, merged