change to flask-sqlalchemy, add map and points
Vixroff/LearnPython_project pull request #8
Opened 2022-06-14 10:31 UTC by Vixroff

Что сделано:

1. Переписано все под flask-sqlalchemy.
2. Добавлен пакет flask-migrates, создано окружение, изменена структура базы.
3. Создан список словарей с координатами зданий и добавлена функция загрузки данных в базу.
4. Прописан новый route.
5. Создан шаблон html, куда добавлена карта с отметками координат наших зданий.

2022-06-15 16:40 UTC, kazauwa requested changes

2022-06-15 16:40 UTC, kazauwa commented on requirements.txt
> +flask-migrate-3.1.0
```suggestion
flask-migrate==3.1.0
```

2022-06-15 16:40 UTC, kazauwa commented on webapp/routes.py
> +    tenants = Sections.session.query.filter_by(tenant_id=id).all()
Почему `tenant_id=id`, если `id` - это айдишник здания?
И кстати, `id()` - это встроенная в питон функция, поэтому переменная с названием `id` будет её перекрывать. Давай-ка переименуем id, например в `building_id`

2022-06-15 16:40 UTC, kazauwa commented on webapp/static/js/script.js
> +ymaps.ready(init)
Этот файл нигде не используется

2022-06-15 16:40 UTC, kazauwa commented on add_data.py
> +coordinates_of_building = [
По заданию координаты надо было доставать из геокодера. Т.е. достать все здания из базы, передать адрес в геокодер, получить координаты и записать в базу.

2022-06-15 16:40 UTC, kazauwa commented on add_data.py
> +    # add_buildings_coordinates(coordinates_of_building)
Если этот код не используется, то его надо удалить.

2022-06-15 16:55 UTC, Vixroff commented on webapp/routes.py
> +    tenants = Sections.session.query.filter_by(tenant_id=id).all()
Здесь все с прошлого pull request собрано, не помню зачем я тут что-то вообще трогал, наверное под flask-alchemy хотел что-то адаптировать

2022-06-15 16:56 UTC, Vixroff commented on webapp/routes.py
> +    tenants = Sections.session.query.filter_by(tenant_id=id).all()
Андрей сейчас над этим работает, думаю, что все изменится

2022-06-15 16:57 UTC, Vixroff commented on webapp/routes.py
> +    tenants = Sections.session.query.filter_by(tenant_id=id).all()
так что заметка ему @Ralaam1

2022-06-15 16:57 UTC, Vixroff commented on webapp/static/js/script.js
> +ymaps.ready(init)
Даа, я оставил на случай использования шаблона в будущем

2022-06-15 17:00 UTC, Vixroff commented on add_data.py
> +coordinates_of_building = [
Здесь соглашусь, что прописал чит. Но есть еще проблема в том, что на самих картах индексы здания располагаются не точно, одного здания и вовсе нет. Поэтому парсить их было бы не достоверно. Но для прокачки скилла, думаю, что пропишу все равно, пусть будет.

2022-06-15 17:04 UTC, Vixroff commented on add_data.py
> +    # add_buildings_coordinates(coordinates_of_building)
а как быть в случае, если нам понадобится что-то добавить в базу снова? вручную

2022-06-15 17:24 UTC, kazauwa commented on webapp/routes.py
> +    tenants = Sections.session.query.filter_by(tenant_id=id).all()
Исправь, пожалуйста, ты, т.к. твоя фича затрагивает этот кусок кода. Заодно поймёшь как он работает)

2022-06-15 17:25 UTC, Vixroff commented on webapp/routes.py
> +    tenants = Sections.session.query.filter_by(tenant_id=id).all()
хорошо)

2022-06-15 17:30 UTC, kazauwa commented on webapp/static/js/script.js
> +ymaps.ready(init)
Но пока шаблона нет, поэтому файл лежит мёртвым грузом. Возможно, он устареет, а возможно и никогда не понадобится, но всё это время будет лежать в репозитории. Если на проект придёт новый человек, он не поймёт зачем этот файл нужен. Понятное дело, что к нам никто новый не придёт, но в работе такое будет происходить.

2022-06-15 17:33 UTC, kazauwa commented on add_data.py
> +coordinates_of_building = [
Окей, принимается
Но тогда надо хотя бы защититься от ситуации, когда ты переделываешь БД, у здания меняется айдишник и в базу записываются неверные координаты. Можно использовать не id а связку улица + номер здание, или что-то такое

2022-06-15 17:34 UTC, kazauwa commented on add_data.py
> +    # add_buildings_coordinates(coordinates_of_building)
А для чего ты его закомментировал?

2022-06-15 20:00 UTC, Vixroff commented on add_data.py
> +    # add_buildings_coordinates(coordinates_of_building)
для Андрея)

2022-06-17 15:32 UTC, kazauwa approved these changes

2022-06-17 15:39 UTC, merged