creating multiple routes
Vixroff/LearnPython_project pull request #9
Opened 2022-06-18 22:44 UTC by Ralaam1

Добавил на главной странице ссылки для аренды помещений и отображению компаний уже арендующих помещения (в теории это для клиентов). В функции фильтра по площадям предоставляется возможность работы только со свободными помещениями, так же обрабатывается исключение отсутствия помещений с интересующей площадью. Так же сразу добавил правку Максима по корректной записи в БД пустых ячеек.

2022-06-19 09:56 UTC, kazauwa commented
Базу данных из коммита надо убрать

2022-06-19 10:55 UTC, kazauwa requested changes

2022-06-19 10:55 UTC, kazauwa commented on webapp/forms.py
> +class Rent_Filter_Form(FlaskForm):
```suggestion
class RentFilterForm(FlaskForm):
```

2022-06-19 10:55 UTC, kazauwa commented on webapp/routes.py
> +from webapp.forms import Rent_Filter_Form
```suggestion
from webapp.forms import RentFilterForm
```

2022-06-19 10:55 UTC, kazauwa commented on webapp/routes.py
> +    form = Rent_Filter_Form()
```suggestion
    form = RentFilterForm()
```

2022-06-19 10:55 UTC, kazauwa commented on webapp/routes.py
> +            try:
Этот try-except лишний, код ниже не выкидывает эксепшенов

2022-06-19 10:55 UTC, kazauwa commented on webapp/routes.py
> +    if request.method == 'POST' and form.area_min.data < form.area_max.data:
Если условие `form.area_min.data < form.area_max.data` не выполняется, то страница просто загрузится заново и даже не выдаст никакой ошибки.

2022-06-19 10:55 UTC, kazauwa commented on webapp/routes.py
> +                result = Sections.query\
Очень сложно читать этот запрос из-за того что он длинный и на каждой новой строке съезжает куда-то.
Вот тебе несколько вариантов как это можно сделать по-другому, выбери какой больше нравится.

```
result = (
    Sections.query.order_by(Sections.building_id)
    .filter(Sections.function == form.func.data)
    .filter(form.area_max.data >= Sections.area, Sections.area >= form.area_min.data)
    .filter(Sections.tenant_id.is_(None))
    .all()
)
```

```
result = Sections.query.order_by(Sections.building_id) \
    .filter(Sections.function == form.func.data) \
    .filter(form.area_max.data >= Sections.area, Sections.area >= form.area_min.data) \
    .filter(Sections.tenant_id.is_(None)) \
    .all()
```

```
result = Sections.query.order_by(
        Sections.building_id,
    ).filter(
        Sections.function == form.func.data,
    ).filter(
        form.area_max.data >= Sections.area,
        Sections.area >= form.area_min.data,
    ).filter(
        Sections.tenant_id.is_(None),
    ).all()
```

2022-06-19 10:55 UTC, kazauwa commented on webapp/routes.py
> +                flash('Нет свободных помещений по вашему запросу, пожалуйста, свяжитесь с нами, и мы поможем Вам с выбором.', category='error')
Здесь гораздо проще будет добавить проверку `if not result:` вместо try-except

2022-06-19 11:06 UTC, Vixroff commented on add_data.py
> +def check_empty(data):
Здесь эта функция должна использоваться в функции add_tenant, когда мы хотим добавить данные из ячейки в колонку tenant_id. 
Определено, что, хоть эта колонка имеет тип int, из пустой ячейки данные в неё заносятся в таком значении  "". Это единственный способ, который мы смогли найти, для того чтобы в отсутсвие данных имело значение NULL. 
В теории вообще можно это функцию ко всем данным применить, потому что я смотрю на таблицу через db browser и вижу большое количество пустых данных, в которых, очевидно, значение тоже "".

2022-06-19 11:13 UTC, Ralaam1 commented on webapp/routes.py
> +    if request.method == 'POST' and form.area_min.data < form.area_max.data:
Оно загружало пустую страницу с формой. Просто коряво отрабатывался поиск по площади. Я не нашёл, как задать валидатор в формах  на обязательноe min <= max

2022-06-19 11:14 UTC, Ralaam1 commented on webapp/routes.py
> +    if request.method == 'POST' and form.area_min.data < form.area_max.data:
А городить огромную функцию из If'ов не хотелось

2022-06-19 11:15 UTC, Ralaam1 commented on webapp/routes.py
> +            try:
Но выдавало просто 500 ошибку. Или try/except только для "....Error" использовать надо?

2022-06-19 12:13 UTC, kazauwa commented on webapp/routes.py
> +    if request.method == 'POST' and form.area_min.data < form.area_max.data:
Я здесь имею в виду, что пользователь никак не узнает о том, почему результат поиска пустой

2022-06-19 12:13 UTC, kazauwa commented on webapp/routes.py
> +            try:
А почему оно выдавало 500-ю ошибку?

2022-06-20 11:33 UTC, kazauwa approved these changes

2022-06-20 11:41 UTC, merged